### PR TITLE
Ignore the PATH fix if it is not set

### LINKED ISSUE #1436: stack ./install.hs stack-install-cabal failed
```
$ stack ./install.hs stack-install-cabal
run from: stack
# stack (for cabal)
# stack (for cabal)
Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:81:69 in shake-0.17.8-42j6WLpuW2RLDjaIMjbO7Y:Development.Shake.Internal.Args
* Depends on: stack-install-cabal
  at need, called at src/HieInstall.hs:94:55 in hie-install-0.8.0.0-217T3gMG2hYDJU1sGHGe5h:HieInstall
* Depends on: cabal
* Raised the exception:
PATH: getEnv: does not exist (no environment variable)
```

### PR DESCRIPTION
**Pull request by jneira**
* If it is not set the fix makes no sense
* Fixes #1436

### CODE REVIEW

File: install/src/Stack.hs [hunk 1]
```diff
@@ -102,7 +104,9 @@ stackBuildFailMsg =
 -- |Run actions without the stack cached binaries 
 withoutStackCachedBinaries :: Action a -> Action a
 withoutStackCachedBinaries action = do
-  mbPath <- liftIO (lookupEnv "PATH")
+  mbPath <- liftIO (catch
+                    (lookupEnv "PATH")
+                    (\(_ :: SomeException) -> return Nothing))
```
Comment (fendor) [inline install/src/Stack.hs]: `SomeException` also catches Async Exceptions. In this case, this may be safe, but it is a bad idea in general.
Please just catch `IOException` (assuming that is the actual exception that is thrown.)

Comment (jneira) [reply install/src/Stack.hs]: Oh, right, thanks for pointed it out

**Comment by fendor** [comment]
In https://github.com/haskell/haskell-ide-engine/issues/1436#issuecomment-550301084 it is said that the path is set. Maybe dont merge this until it is clear why this issue arises?

**Comment by jneira** [comment]
> In #1436 (comment) it is said that the path is set. Maybe dont merge this until it is clear why this issue arises?

Sure, but i think the actual code does what i expected in the fisrt place (return `Nothing` if the var is not informed)

> Is catching an exception the best way to detect if the environment variable is set? This seems a bit hacky to me, but I have no experience with the System.Environment module

It was a surprise to me that `lookupEnv` throws an Exception instead `Nothing` if the variable is not set (why return `Maybe String` then?)

The [docs ](http://hackage.haskell.org/package/base-4.12.0.0/docs/System-Environment.html#v:lookupEnv) for `lookupEnv` states:
> For POSIX users, this is equivalent to getEnv.

...and `getenv` trhows an IOException if the variable is not set  🤦‍♂

**Comment by fendor** [comment]
>
>
> ...and getenv trhows an IOException if the variable is not set 🤦‍♂

then the patch makes sense. Maybe we should only catch exceptions that satisfy the predicate `isDoesNotExistError`? Otherwise, this PR is good to go.

**Comment by fendor** [comment]
@jneira Merge when you are ready!
