### PR TITLE
Handling Windows specific delimiters in func tests

### LINKED ISSUE #1391: Error in windows detected by the functional test suite
The test suite fails in my windows 10 msys2 console with those errors:

```
Failures:

  test/functional\\FunctionalCodeActionsSpec.hs:110:16:
  1) FunctionalCodeActions, code actions, rename suggestions, works
       expected: "main = putStrLn \"hello\""
        but got: "main =  \"hello\""

  To rerun use: --match "/FunctionalCodeActions/code actions/rename suggestions/works/"

  test/functional\\FunctionalCodeActionsSpec.hs:127:18:
  2) FunctionalCodeActions, code actions, rename suggestions, doesn't give both documentChanges and changes
       expected: "foo = putStrLn \"world\""
        but got: "foo =  \"world\""

  To rerun use: --match "/FunctionalCodeActions/code actions/rename suggestions/doesn't give both documentChanges and changes/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  3) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, multiple import-list formats
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: ["Replace with "]
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module System.IO (stdout)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/multiple import-list formats/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  4) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, respects format config, multiple import-list
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: ["Replace with "]
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module System.IO (stdout)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/respects format config, multiple import-list/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  5) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, complex import-list
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: []
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)","Import module Data.Function (($))","Import module Data.Maybe (Maybe (Just))","Import module Prelude (Bool (..))","Import module System.IO (stderr)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/complex import-list/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  6) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, complex import-list respects format config
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: []
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)","Import module Data.Function (($))","Import module Data.Maybe (Maybe (Just))","Import module Prelude (Bool (..))","Import module System.IO (stderr)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/complex import-list respects format config/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  7) FunctionalCodeActions, code actions, import suggestions, formats with floskell, Execute HsImport with formatter floskell, multiple import-list formats
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: ["Replace with "]
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module System.IO (stdout)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with floskell/Execute HsImport with formatter floskell/multiple import-list formats/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  8) FunctionalCodeActions, code actions, import suggestions, formats with floskell, Execute HsImport with formatter floskell, respects format config, multiple import-list
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: ["Replace with "]
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module System.IO (stdout)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with floskell/Execute HsImport with formatter floskell/respects format config, multiple import-list/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  9) FunctionalCodeActions, code actions, import suggestions, formats with floskell, Execute HsImport with formatter floskell, complex import-list
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: []
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)","Import module Data.Function (($))","Import module Data.Maybe (Maybe (Just))","Import module Prelude (Bool (..))","Import module System.IO (stderr)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with floskell/Execute HsImport with formatter floskell/complex import-list/"

  test/functional\\FunctionalCodeActionsSpec.hs:729:11:
  10) FunctionalCodeActions, code actions, import suggestions, formats with floskell, Execute HsImport with formatter floskell, complex import-list respects format config
       uncaught exception: ErrorCall
       No action found to be executed!
        Actual actions titles: []
        Expected actions titles: ["Import module System.IO (hPutStrLn)","Import module Control.Monad (when)","Import module Data.Maybe (fromMaybe)","Import module Data.Function (($))","Import module Data.Maybe (Maybe (Just))","Import module Prelude (Bool (..))","Import module System.IO (stderr)"]
       CallStack (from HasCallStack):
         error, called at test/functional\\FunctionalCodeActionsSpec.hs:729:11 in main:FunctionalCodeActionsSpec

  To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with floskell/Execute HsImport with formatter floskell/complex import-list respects format config/"

  test/functional\\FunctionalCodeActionsSpec.hs:226:20:
  11) FunctionalCodeActions, code actions, add package suggestions, adds to .cabal files
       predicate failed on: "Could not load module `Data.Text'\nIt is a member of the hidden package `text-1.2.3.1'.\nPerhaps you need to add `text' to the build-depends in your .cabal file.\nUse -v to see a list of the files searched for."

  To rerun use: --match "/FunctionalCodeActions/code actions/add package suggestions/adds to .cabal files/"

  test/functional\\FunctionalCodeActionsSpec.hs:253:23:
  12) FunctionalCodeActions, code actions, add package suggestions, adds to hpack package.yaml files
       predicate failed on: "Could not find module `Codec.Compression.GZip'\nUse -v to see a list of the files searched for."

  To rerun use: --match "/FunctionalCodeActions/code actions/add package suggestions/adds to hpack package.yaml files/"

  test/functional\\FunctionalCodeActionsSpec.hs:282:18:
  13) FunctionalCodeActions, code actions, redundant import code actions, remove solitary redundant imports
       predicate failed on: "The import of `Data.List' is redundant\n  except perhaps to import instances from `Data.List'\nTo import instances alone, use: import Data.List()"

  To rerun use: --match "/FunctionalCodeActions/code actions/redundant import code actions/remove solitary redundant imports/"

  test/functional\\FunctionalCodeActionsSpec.hs:302:5:
  14) FunctionalCodeActions, code actions, redundant import code actions, doesn't touch other imports
       uncaught exception: SessionException
       Language server unexpectedly terminated

  To rerun use: --match "/FunctionalCodeActions/code actions/redundant import code actions/doesn't touch other imports/"

  test/functional\\FunctionalCodeActionsSpec.hs:332:26:
  15) FunctionalCodeActions, code actions, typed hole code actions, works
       Actual list is not a permutation of expected list!
         expected list contains:   ["Substitute hole (Int) with x ([Int])", "Substitute hole (Int) with foo ([Int] -> Int Valid hole fits include)", "Substitute hole (Int) with maxBound (forall a. Bounded a => a with maxBound @Int)", "Substitute hole (Int) with minBound (forall a. Bounded a => a with minBound @Int)"]
         actual list contains:     ["Substitute hole (Int) with x ([Int])", "Substitute hole (Int) with foo ([Int] -> Int)", "Substitute hole (Int) with maxBound (forall a. Bounded a => a with maxBound @Int)", "Substitute hole (Int) with minBound (forall a. Bounded a => a with minBound @Int)"]
         the missing elements are: ["Substitute hole (Int) with foo ([Int] -> Int Valid hole fits include)"]
         the extra elements are:   ["Substitute hole (Int) with foo ([Int] -> Int)"]

  To rerun use: --match "/FunctionalCodeActions/code actions/typed hole code actions/works/"

  test/functional\\FunctionalCodeActionsSpec.hs:480:18:
  16) FunctionalCodeActions, code actions, unused term code actions, Prefixes with '_'
       ["Prefix  with _","Lift imUnused one level","Lift imUnused to top level","Demote imUnused one level","Delete definition of imUnused","Duplicate definition of imUnused"] does not contain ["Prefix imUnused with _"]

  To rerun use: --match "/FunctionalCodeActions/code actions/unused term code actions/Prefixes with '_'/"
```
I opened this to track them and hopefully help to fix them!

### PR DESCRIPTION
**Pull request by jneira**
* More test fixes (the last ones!) taking in account windows specific delimiters
* This time they need to being added in tests themselves
* Fixes #1391

### CODE REVIEW

File: test/functional/FunctionalCodeActionsSpec.hs [hunk 1]
```diff
@@ -221,11 +221,12 @@ spec = describe "code actions" $ do
...
-      if ghcVersion == GHC86
-        then
-          liftIO $ diag ^. L.message `shouldSatisfy` T.isPrefixOf "Could not load module \8216Data.Text\8217"
-         else
-          liftIO $ diag ^. L.message `shouldSatisfy` T.isPrefixOf "Could not find module ‘Data.Text’"
+      let prefixes = [ "Could not load module `Data.Text'" -- Windows && GHC >= 8.6
+                     , "Could not find module `Data.Text'" -- Windows
+                     , "Could not load module ‘Data.Text’" -- GHC >= 8.6
+                     , "Could not find module ‘Data.Text’"
+                     ]
```
Comment (alanz) [inline test/functional/FunctionalCodeActionsSpec.hs]: Shouldn't we have some uniform way of dealing with the set of quotes? Perhaps run the expected string through a normaliser and then match on the result?
