### PR TITLE
Fix extra newline being added when formatting document

### LINKED ISSUE #521: Formatting code adds newline at the end of the file
As the title reads, newlines are inserted at the end of the file each time I format the code. This problem occurs in VS Code and Emacs at least.

### PR DESCRIPTION
**Pull request by Bubba**
Fixes #521

### CODE REVIEW

File: src/Haskell/Ide/Engine/Plugin/Brittany.hs [hunk 1]
```diff
@@ -44,7 +46,8 @@ brittanyCmd tabSize uri range =
                 l = length textLines
                 c = T.length $ last textLines
                 textLines = T.lines text
-                textEdit = J.TextEdit (Range startPos endPos) newText
+                newTextWithoutNewline = T.init newText -- get rid of extraneous \n
```
Comment (wz1000) [inline src/Haskell/Ide/Engine/Plugin/Brittany.hs]: Wouldn't it be a better idea to remove all trailing newlines specifically instead of blindly truncating the text?

Comment (Bubba) [reply src/Haskell/Ide/Engine/Plugin/Brittany.hs]: Probably! Brittany seems to only remove the first trailing newline though, so should we try to match this?

**Comment by lspitzner** [comment]
The use of `T.lines` above looks suspicious to me, btw. Afaict, `T.lines` interprets "newline" as purely "\n" and leaves "\r" in place. I have not considered/tested the exact consequences of this, but it seems not all unlikely to be behind this newline bug and also potentially other newline insertion problems that were reported for HIE.

@Bubba Unrelated: Under what circumstances does brittany remove trailing newlines?

**Comment by alanz** [comment]
@lspitzner what do we do with this PR?

**Comment by lspitzner** [comment]
I cannot reproduce the issue with `readFile`:

~~~~
> :!hexdump -C test.txt
00000000  66 69 72 73 74 0d 0a 73  65 63 6f 6e 64           |first..second|
0000000d
> TIO.readFile "test.txt"
"first\r\nsecond"
~~~~

I also point out that it is really hard to tell from

> ~~~~
> > cat test
> hello world
> this is a test with no newline
> ~~~~

whether the file actually terminates with a newline. It really should look like this:

~~~~
> cat test
hello world
this is a test with no newline> [cursor here]
~~~~

**Comment by lspitzner** [comment]
As this might be system/locale dependent, I should add that I have tested on linux only, with "\n" and "\r\n". @Bubba what environment are you seeing this in?

**Comment by Bubba** [comment]
Sorry, disregard what I said about `T.readFile`! I was naïve to think that echoing to a file wouldn't add a newline. I'm on macOS 10.13. I will try to figure out more about what is exactly causing this.

**Comment by Bubba** [comment]
What I'm now convinced was happening is that the range of text being replaced didn't include the last newline character, which meant that it stayed around after the formatted text was inserted, adding an extra line. [From the specification:](https://microsoft.github.io/language-server-protocol/specification#range)
> If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.

Although I found that the end range column needs to be past zero, contradictory to above. This was tested on VS Code.

**Comment by wz1000** [comment]
The Position type is zero indexed(as specified by LSP), but the tuple (Int,Int) is assumed to always be one indexed in HIE(as GHC reports positions as one indexed tuples). `toPos :: (Int, Int) -> Position` converts between these two representations. So

    toPos (1,1) == Position 0 0

The mixing of types here is unfortunate(probably my fault, and how this bug originated). It would be better to use one of these position types consistently here.

Otherwise it looks good.
